export const weatherCodeToAdvice = {
    0: "Perfect hiking weather, but still take care. Wear light, breathable layers and comfortable walking boots. Bring sunglasses, a hat, and sunscreen - even in the UK, UV can be strong on exposed hills and ridges. Carry at least 1-2L of water, especially on longer walks, and don't forget a light extra layer in case temperatures drop later or on higher ground.",

    1: "Generally fine for walking. Dress in light to medium layers that you can add or remove as the cloud cover changes. A thin waterproof or windproof jacket is still a good idea in case of passing showers or chilly winds on exposed tops. Visibility is usually good, but cloud can drop quickly in the Peak District, so always carry a map/compass or reliable offline navigation.",
    2: "Generally fine for walking. Dress in light to medium layers that you can add or remove as the cloud cover changes. A thin waterproof or windproof jacket is still a good idea in case of passing showers or chilly winds on exposed tops. Visibility is usually good, but cloud can drop quickly in the Peak District, so always carry a map/compass or reliable offline navigation.",
    3: "Generally fine for walking. Dress in light to medium layers that you can add or remove as the cloud cover changes. A thin waterproof or windproof jacket is still a good idea in case of passing showers or chilly winds on exposed tops. Visibility is usually good, but cloud can drop quickly in the Peak District, so always carry a map/compass or reliable offline navigation.",

    45: "Fog makes navigation much harder, especially on open moorland and plateaus. Only attempt longer or higher-level walks if you are confident with map and compass, and have a charged phone with offline maps as backup. Wear warm, moisture-wicking layers and a waterproof outer, as fog and rime will make everything damp and chilly. Rocks, flagstones, and wooden styles/bridges can be very slippery. If visibility is very poor, consider a lower-level route or shortening your walk.",
    48: "Fog makes navigation much harder, especially on open moorland and plateaus. Only attempt longer or higher-level walks if you are confident with map and compass, and have a charged phone with offline maps as backup. Wear warm, moisture-wicking layers and a waterproof outer, as fog and rime will make everything damp and chilly. Rocks, flagstones, and wooden styles/bridges can be very slippery. If visibility is very poor, consider a lower-level route or shortening your walk.",

    51: "Wear a waterproof jacket with a hood and ideally waterproof trousers; drizzle can soak through clothing slowly but thoroughly. Good grippy hiking boots are important, as rocks, roots, and muddy paths will be slick. Pack a warm mid-layer, hat, and thin gloves - drizzle plus wind can feel much colder than the temperature suggests. Consider a shorter or lower-level walk if the ground is already very wet.",
    53: "Wear a waterproof jacket with a hood and ideally waterproof trousers; drizzle can soak through clothing slowly but thoroughly. Good grippy hiking boots are important, as rocks, roots, and muddy paths will be slick. Pack a warm mid-layer, hat, and thin gloves - drizzle plus wind can feel much colder than the temperature suggests. Consider a shorter or lower-level walk if the ground is already very wet.",
    55: "Wear a waterproof jacket with a hood and ideally waterproof trousers; drizzle can soak through clothing slowly but thoroughly. Good grippy hiking boots are important, as rocks, roots, and muddy paths will be slick. Pack a warm mid-layer, hat, and thin gloves - drizzle plus wind can feel much colder than the temperature suggests. Consider a shorter or lower-level walk if the ground is already very wet.",

    56: "This is cold, damp, and potentially icy - conditions can be deceptively dangerous. Wear a fully waterproof shell plus insulating layers underneath (fleece or insulated jacket), a hat, and warm gloves. Expect extremely slippery surfaces: rocks, flagstones, wooden bridges, and even grassy slopes can ice up. Consider using trekking poles for stability. Avoid steep rocky scrambles or exposed edges; if paths look glazed or icy, turning back is the safest option.",
    57: "This is cold, damp, and potentially icy - conditions can be deceptively dangerous. Wear a fully waterproof shell plus insulating layers underneath (fleece or insulated jacket), a hat, and warm gloves. Expect extremely slippery surfaces: rocks, flagstones, wooden bridges, and even grassy slopes can ice up. Consider using trekking poles for stability. Avoid steep rocky scrambles or exposed edges; if paths look glazed or icy, turning back is the safest option.",

    61: "You'll want a proper waterproof jacket (not just “showerproof”), waterproof trousers, and reliable boots - ideally with a waterproof membrane. Pack spare dry layers in a dry bag inside your rucksack. In moderate to heavy rain, streams and becks can rise quickly; avoid crossing fast-flowing water and be cautious in narrow valleys where paths can flood. Expect very muddy conditions; consider choosing a well-made path or more straightforward route rather than a long, boggy moorland hike.",
    63: "You'll want a proper waterproof jacket (not just “showerproof”), waterproof trousers, and reliable boots - ideally with a waterproof membrane. Pack spare dry layers in a dry bag inside your rucksack. In moderate to heavy rain, streams and becks can rise quickly; avoid crossing fast-flowing water and be cautious in narrow valleys where paths can flood. Expect very muddy conditions; consider choosing a well-made path or more straightforward route rather than a long, boggy moorland hike.",
    65: "You'll want a proper waterproof jacket (not just “showerproof”), waterproof trousers, and reliable boots - ideally with a waterproof membrane. Pack spare dry layers in a dry bag inside your rucksack. In moderate to heavy rain, streams and becks can rise quickly; avoid crossing fast-flowing water and be cautious in narrow valleys where paths can flood. Expect very muddy conditions; consider choosing a well-made path or more straightforward route rather than a long, boggy moorland hike.",

    66: "Freezing rain is seriously hazardous - it can turn paths, rocks, and roads into sheets of ice. Avoid high or exposed routes and strongly consider postponing your hike or choosing a very short, low-level walk close to safety. If you do go out, wear full waterproofs and insulating layers, hat, and warm gloves. Use hiking poles for balance, and be extremely cautious on any descent, stepping on grass rather than rocks where possible. In many cases, the safest advice is: don't hike in the hills during freezing rain.",
    67: "Freezing rain is seriously hazardous - it can turn paths, rocks, and roads into sheets of ice. Avoid high or exposed routes and strongly consider postponing your hike or choosing a very short, low-level walk close to safety. If you do go out, wear full waterproofs and insulating layers, hat, and warm gloves. Use hiking poles for balance, and be extremely cautious on any descent, stepping on grass rather than rocks where possible. In many cases, the safest advice is: don't hike in the hills during freezing rain.",

    71: "Snow can be beautiful but demanding. Wear warm, layered clothing (base layer, mid-layer, insulated or fleece jacket) plus a waterproof/windproof shell, hat, scarf/buff, and insulated gloves. Waterproof boots with good tread are essential; gaiters can help keep snow out. Navigation becomes much more difficult in snow, especially if paths are covered, so only attempt exposed or high routes if you're experienced and well-equipped. Heavy snowfall can hide edges, bogs, and streams - stick to familiar or well-marked routes. If conditions deteriorate or you're unsure of your line, turn back early.",
    73: "Snow can be beautiful but demanding. Wear warm, layered clothing (base layer, mid-layer, insulated or fleece jacket) plus a waterproof/windproof shell, hat, scarf/buff, and insulated gloves. Waterproof boots with good tread are essential; gaiters can help keep snow out. Navigation becomes much more difficult in snow, especially if paths are covered, so only attempt exposed or high routes if you're experienced and well-equipped. Heavy snowfall can hide edges, bogs, and streams - stick to familiar or well-marked routes. If conditions deteriorate or you're unsure of your line, turn back early.",
    75: "Snow can be beautiful but demanding. Wear warm, layered clothing (base layer, mid-layer, insulated or fleece jacket) plus a waterproof/windproof shell, hat, scarf/buff, and insulated gloves. Waterproof boots with good tread are essential; gaiters can help keep snow out. Navigation becomes much more difficult in snow, especially if paths are covered, so only attempt exposed or high routes if you're experienced and well-equipped. Heavy snowfall can hide edges, bogs, and streams - stick to familiar or well-marked routes. If conditions deteriorate or you're unsure of your line, turn back early.",

    77: "Snow grains often come with cold, cloudy, and sometimes windy conditions. Treat it like light snow plus icy drizzle: wear warm layers, waterproof outer shell, hat, and gloves. Expect surfaces to be slippery and visibility to be reduced at times. Avoid steep or rocky sections if the ground is icy, and plan a shorter or less committing route. Keep an eye on how cold and wet you're getting - hypothermia can creep up in these conditions.",

    80: "Showery conditions are very changeable - you might get bursts of heavy rain and then bright spells. Wear a breathable waterproof jacket and consider quick-dry trousers (with waterproof overtrousers in your bag). Use a waterproof cover or dry bag for your kit. In heavy or “violent” showers, visibility can temporarily drop and paths can flood or turn very muddy. If a shower becomes intense, it can be worth pausing in a sheltered spot until it passes. Be cautious on rocky sections immediately after a violent shower - surfaces will be slick.",
    81: "Showery conditions are very changeable - you might get bursts of heavy rain and then bright spells. Wear a breathable waterproof jacket and consider quick-dry trousers (with waterproof overtrousers in your bag). Use a waterproof cover or dry bag for your kit. In heavy or “violent” showers, visibility can temporarily drop and paths can flood or turn very muddy. If a shower becomes intense, it can be worth pausing in a sheltered spot until it passes. Be cautious on rocky sections immediately after a violent shower - surfaces will be slick.",
    82: "Showery conditions are very changeable - you might get bursts of heavy rain and then bright spells. Wear a breathable waterproof jacket and consider quick-dry trousers (with waterproof overtrousers in your bag). Use a waterproof cover or dry bag for your kit. In heavy or “violent” showers, visibility can temporarily drop and paths can flood or turn very muddy. If a shower becomes intense, it can be worth pausing in a sheltered spot until it passes. Be cautious on rocky sections immediately after a violent shower - surfaces will be slick.",

    85: "Similar to rain showers, but colder and more serious. Wear full winter layers: thermal base layer, warm mid-layer, insulated or fleece jacket, waterproof shell, hat, and warm gloves. Expect sudden changes in visibility: one minute you can see the ridge, the next you're in a white curtain. This makes navigation tricky, especially on featureless moorland or plateaus. Stick to clear, well-defined routes unless you're experienced in winter navigation. Heavy showers can quickly lay down fresh snow, hiding paths and increasing slip risk.",
    86: "Similar to rain showers, but colder and more serious. Wear full winter layers: thermal base layer, warm mid-layer, insulated or fleece jacket, waterproof shell, hat, and warm gloves. Expect sudden changes in visibility: one minute you can see the ridge, the next you're in a white curtain. This makes navigation tricky, especially on featureless moorland or plateaus. Stick to clear, well-defined routes unless you're experienced in winter navigation. Heavy showers can quickly lay down fresh snow, hiding paths and increasing slip risk.",

    95: "Thunderstorms are dangerous in exposed terrain. Avoid ridges, summits, trig points, and open moorland during a storm. If thunderstorms are in the forecast for your walking window, consider doing a short, lower-level walk where you can quickly reach shelter, or rescheduling. If you're caught out and hear thunder, move away from high ground, isolated trees, metal fences, and crags; head for lower, less exposed terrain. Rainfall can be intense with thunderstorms, so expect very wet and slippery paths, and possible flash flooding in narrow valleys or by streams.",

    96: "This is some of the worst hiking weather: lightning, strong rain, and hail that can be painful and make the ground extremely slippery. Best advice: don't plan a Peak District hike in this if you can avoid it. If you're already out and a hail thunderstorm hits, get off high/exposed ground as quickly and safely as possible and avoid summits, ridges, and lone trees. Protect your head with a hood or hat; hail can reduce visibility and make rocks/paths treacherous. Wait for the worst of the storm to pass before continuing, and be ready to cut the walk short.",
    99: "This is some of the worst hiking weather: lightning, strong rain, and hail that can be painful and make the ground extremely slippery. Best advice: don't plan a Peak District hike in this if you can avoid it. If you're already out and a hail thunderstorm hits, get off high/exposed ground as quickly and safely as possible and avoid summits, ridges, and lone trees. Protect your head with a hood or hat; hail can reduce visibility and make rocks/paths treacherous. Wait for the worst of the storm to pass before continuing, and be ready to cut the walk short.",
}